using one wallpaper source from a soft-link

diff --git a/bin/bspTheme b/bin/bspTheme
--- a/bin/bspTheme
+++ b/bin/bspTheme
@@ -1,15 +1,14 @@
 #!/bin/bash
 # using pywal
-override=$1 # means must regen wal even if it is gened
-walToggle=0 # means must regen wal if alreay gened, no need 
-nowal=0     # means cannot find pywal
-backend=$(cat ~/.backend) # the backend to use 
+override=$1               # means must regen wal even if it is gened
+walToggle=0               # means must regen wal if alreay gened, no need
+backend=$(cat ~/.backend) # the backend to use
 wallpaperdir="$HOME/.config/bspwm/wallpaper/wallpaper.png"
 DIR="$HOME/.config/bspwm/"
 
 ## -_-_-_-_-_-_-_-_-_ Source wal colors -_-_-_-_-_-_-_-_-_ ##
 
-# source the color wal generated 
+# source the color wal generated
 function sourcewal() {
 	echo -e "\e[32m[*] \e[0mApplying Theme"
 	[ -f "$HOME/.cache/wal/colors.sh" ] && source "$HOME/.cache/wal/colors.sh" || walToggle=1
@@ -18,57 +17,23 @@ function sourcewal() {
 ### getting the theme colors
 sourcewal
 
-### checks 
+### checks
 if [ $walToggle -eq 1 ] || [ "$override" != "" ]; then
 	[ -f "$wallpaperdir" ] && [ -f /bin/wal ] && wal -c || {
 		echo "wall not installed or wallpaper not found"
-		nowal=1
+		exit 1
 	}
 
-	if [ $nowal -eq 0 ];then ## pywal was found
-		echo -e "\e[32m[*] \e[0mSetting wallpaper..."
-		cp "$wallpaperdir" "$HOME/.wallpaper.png" 2>>~/log.txt
-		[ "$backend" = "" ] && backend="wal"
-		wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt || {
-			echo "wallpaper or wal not found exiting..."
-			exit 1
-		}
-		echo -e "\e[32m[*] \e[0mGenerating Theme..."
-		sourcewal
-	else ### pywal was not found, hardcode colors 
-	
-	wallpaper="$HOME/.config/bspwm/wallpaper/beach.png"
-
-	# Special
-	background='#21222b'
-	foreground='#dadbd4'
-	cursor='#dadbd4'
-	# Colors
-	color0='#21222b'
-	color1='#797E81'
-	color2='#7D8284'
-	color3='#898C8E'
-	color4='#A0A29D'
-	color5='#B4B6AD'
-	color6='#BEC0B5'
-	color7='#dadbd4'
-	color8='#989994'
-	color9='#797E81'
-	color10='#7D8284'
-	color11='#898C8E'
-	color12='#A0A29D'
-	color13='#B4B6AD'
-	color14='#BEC0B5'
-	color15='#dadbd4'
-	# FZF colors
-	export FZF_DEFAULT_OPTS="
-	    $FZF_DEFAULT_OPTS
-	    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
-	    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
-	"
-	# Fix LS_COLORS being unreadable.
-	export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
-	fi
+	echo -e "\e[32m[*] \e[0mSetting wallpaper..."
+	cp "$wallpaperdir" "$HOME/.wallpaper.png" >>~/log.txt 2>&1
+	[ "$backend" = "" ] && backend="wal"
+	wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1 || {
+		echo "wallpaper or backend not found using default: wal"
+		echo "wal" >~/.backend && backend="wal"
+		wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1
+	}
+	echo -e "\e[32m[*] \e[0mGenerating Theme..."
+	sourcewal
 
 fi
 
@@ -109,6 +74,20 @@ polybarTheme() {
 		green =         ${GREEN}
 		yellow =        ${YELLOW}
 	EOF
+}
+
+## Write i3colors
+i3Theme() {
+	echo -e "\e[32m[*] \e[0mApplying colors to i3"
+	cat >"$DIR"/i3colors <<-_EOF_
+		# class                 border  backgr. text    indicator child_border
+		client.focused          #DA6E89 #DA6E89 #FFFFFF #98C379   #DA6E89
+		client.focused_inactive #61AFEF #61AFEF #1E222A #98C379   #61AFEF
+		client.unfocused        #2C3038 #2C3038 #FFFFFF #98C379   #2C3038
+		client.urgent           #C678DD #C678DD #FFFFFF #98C379   #C678DD
+		client.placeholder      #1E222A #1E222A #FFFFFF #98C379   #1E222A
+		client.background       #1E222A
+	_EOF_
 }
 
 ## Write alacritty colors.yml file with current theme colors
@@ -191,7 +170,7 @@ dunstTheme() {
 }
 
 firefoxTheme() {
-	echo -e "\e[32m[*] \e[0mApplying colors to Firfox"
+	echo -e "\e[32m[*] \e[0mApplying colors to Firefox"
 	[ -f /bin/firefox ] && [ -f /bin/pywalfox ] && [ -f /bin/wal ] && pywalfox install >/dev/null 2>&1 || echo -e "\e[32m[ERR] \e[0mfirefox pywal failed or not found\n"
 }
 
