changed colorscheme

diff --git a/bin/bspTheme b/bin/bspTheme
--- a/bin/bspTheme
+++ b/bin/bspTheme
@@ -1,17 +1,25 @@
 #!/bin/bash
 # using pywal
+override=$1
 walToggle=0
-wallpaperdir="$HOME/.config/bspwm/others/wallpaper/wallpaper.jpg"
+wallpaperdir="$HOME/.config/bspwm/others/wallpaper/wallpaper.png"
 DIR="$HOME/.config/bspwm/"
+
 ## -_-_-_-_-_-_-_-_-_ Source wal colors -_-_-_-_-_-_-_-_-_ ##
+
 function sourcewal() {
+	echo -e "\e[32m [*] \e[0mApplying Theme"
 	[ -f "$HOME/.cache/wal/colors.sh" ] && source "$HOME/.cache/wal/colors.sh" || walToggle=1
 }
 ### getting the theme colors
 sourcewal
 
-if [ $walToggle -eq 1 ]; then
-	[ -f "$wallpaperdir" ] && [ -f /bin/wal ] && wal -i "$wallpaperdir" || exit 1
+if [ $walToggle -eq 1 ] || [ $override -ne 0 ]; then
+	[ -f "$wallpaperdir" ] && [ -f /bin/wal ] && wal -i "$wallpaperdir" || {
+		echo "wallpaper or wal not found exiting..."
+		exit 1
+	}
+	echo -e "\e[32m [*] \e[0mGenerating Theme"
 	sourcewal
 fi
 
@@ -40,21 +48,23 @@ getcolors() {
 
 ## Write polybar colors file with current theme colors
 polybarTheme() {
+	echo -e "\e[32m [*] \e[0mApplying colors to polybar"
 	cat >"$DIR"/polybar/colors.ini <<-EOF
 		[color]
 		foreground = ${FOREGROUND}
 		background = ${BACKGROUND}
-		    primary = ${CURSOR}
-		    ; workspace color
-		    workcolor = ${FOREGROUND} 
+		primary = ${CURSOR}
+		;workspace color
+		workcolor = ${FOREGROUND} 
 		red = ${RED}
 		green = ${GREEN}
-		    yellow = ${YELLOW}
+		yellow = ${YELLOW}
 	EOF
 }
 
 ## Write alacritty colors.yml file with current theme colors
 alacrittyTheme() {
+	echo -e "\e[32m [*] \e[0mApplying colors to Alacritty"
 	cat >"$DIR"/alacritty/colors.yml <<-_EOF_
 		## Colors configuration
 		colors:
@@ -87,15 +97,17 @@ alacrittyTheme() {
 	_EOF_
 }
 kittyTheme() {
+	echo -e "\e[32m [*] \e[0mApplying colors to Kitty"
 	[ -f ~/.cache/wal/colors-kitty.conf ] && cp ~/.cache/wal/colors-kitty.conf ../kitty/color.conf
 }
 
 ## Write rofi colors.rasi file with current theme colors
 rofiTheme() {
+	echo -e "\e[32m [*] \e[0mApplying colors to rofi"
 	cat >"$DIR"/rofi/dependencies/colors.rasi <<-EOF
 		* {
 		    background:   ${BACKGROUND};
-		        background-alt:     ${CURSOR};
+		    background-alt:     ${CURSOR};
 		    foreground:   ${FOREGROUND};
 		    selected:     ${BLUE};
 		    active:       ${YELLOW};
@@ -106,6 +118,7 @@ rofiTheme() {
 
 ## Write dunstrc file with current theme colors
 dunstTheme() {
+	echo -e "\e[32m [*] \e[0mApplying colors to dunst"
 	sed -i '/urgency_low/Q' "$DIR"/others/dunstrc
 	cat >>"$DIR"/others/dunstrc <<-_EOF_
 		[urgency_low]
@@ -129,7 +142,8 @@ dunstTheme() {
 }
 
 firefoxTheme() {
-	[ -f /bin/firefox ] && [ -f /bin/pywalfox ] && [ -f /bin/wal ] && pywalfox install || echo "firefox pywal failed or not found\n"
+	echo -e "\e[32m [*] \e[0mApplying colors to Firfox"
+	[ -f /bin/firefox ] && [ -f /bin/pywalfox ] && [ -f /bin/wal ] && pywalfox install >/dev/null 2>&1 || echo "firefox pywal failed or not found\n"
 }
 
 ## Execute functions and run main
